# -*- mode: ruby -*-
# vi: set ft=ruby :

$prompt = <<SCRIPT
echo 'export PS1="\e[0;33m<\e[m\e[0;31mdemo\e[m\e[0;33m@\e[m\e[0;31mnsm\e[m\e[0;33m>\e[m \e[0;33m[\e[m\w\e[0;33m]\e[m: "' > /etc/profile.d/prompt.sh
chmod 755 /etc/profile.d/prompt.sh
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  # Used in videos, requires physical #nterface
  #config.vm.network "public_network", bridge: 'en0: Ethernet Alias'

  #config.vm.provision "shell", inline: $prompt
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.synced_folder "../data", "/vagrant_data"

   config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "nsm-ubuntu"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
   end

end
